/*
 * Copyright © 2026 RTAkland
 * Author: RTAkland
 * Date: 2026/9/5
 */

package cn.rtast.libmc.protocol.protocol

import cn.rtast.libmc.protocol.packet.configuration.clientbound.*
import cn.rtast.libmc.protocol.packet.configuration.serverbound.*
import cn.rtast.libmc.protocol.packet.handshake.ServerboundHandshakePacket
import cn.rtast.libmc.protocol.packet.login.clientbound.*
import cn.rtast.libmc.protocol.packet.login.serverbound.ServerboundCustomQueryAnswerPacket
import cn.rtast.libmc.protocol.packet.login.serverbound.ServerboundKeyPacket
import cn.rtast.libmc.protocol.packet.login.serverbound.ServerboundLoginAcknowledgedPacket
import cn.rtast.libmc.protocol.packet.login.serverbound.ServerboundLoginStartPacket
import cn.rtast.libmc.protocol.packet.play.clientbound.*
import cn.rtast.libmc.protocol.packet.play.serverbound.*
import cn.rtast.libmc.protocol.packet.status.clientbound.ClientboundPongResponsePacket
import cn.rtast.libmc.protocol.packet.status.clientbound.ClientboundStatusResponsePacket
import cn.rtast.libmc.protocol.packet.status.serverbound.ServerboundPingRequestPacket
import cn.rtast.libmc.protocol.packet.status.serverbound.ServerboundStatusRequestPacket
import cn.rtast.libmc.protocol.protocol.state.ProtocolState
import cn.rtast.libmc.protocol.protocol.state.ProtocolStateRegistry

internal object GamePacketsProtocolCodec {
    val clientboundGameProtocols = ProtocolStateRegistry().apply {
        register(ProtocolState.STATUS) {
            register(0x00, ClientboundStatusResponsePacket)
            register(0x01, ClientboundPongResponsePacket)
        }
        register(ProtocolState.LOGIN) {
            register(0x00, ClientboundDisconnectLoginPacket)
            register(0x01, ClientboundHelloPacket)
            register(0x02, ClientboundLoginSuccessPacket)
            register(0x03, ClientboundSetCompressionPacket)
            register(0x04, ClientboundCustomQueryPacket)
            register(0x05, ClientboundCookieRequestPacket)
        }
        register(ProtocolState.CONFIGURATION) {
            register(0x00, ClientboundCookieRequestPacket)
            register(0x01, ClientboundCustomPayloadPacket)
            register(0x02, ClientboundDisconnectConfigurationPacket)
            register(0x03, ClientboundFinishConfigurationPacket)
            register(0x04, ClientboundKeepAliveConfigurationPacket)
            register(0x05, ClientboundPingConfigurationPacket)
            register(0x06, ClientboundResetChatPacket)
            register(0x07, ClientboundRegistryDataPacket)
            register(0x08, ClientboundRemoveResourcePackPacket)
            register(0x09, ClientboundAddResourcePackPacket)
            register(0x0A, ClientboundStoreCookiePacket)
            register(0x0B, ClientboundTransferPacket)
            register(0x0C, ClientboundUpdateEnabledFeaturesPacket)
            register(0x0D, ClientboundUpdateTagsPacket)
            register(0x0E, ClientboundSelectKnownPacksPacket)
            register(0x0F, ClientboundCustomReportDetailsPacket)
            register(0x10, ClientboundServerLinksPacket)
            register(0x11, ClientboundClearDialogPacket)
            register(0x12, ClientboundConfigurationShowDialogPacket)
            register(0x13, ClientboundCodeOfConductPacket)
        }
        register(ProtocolState.PLAY) {
            register(0x00, ClientboundDelimiterPacket)
            register(0x01, ClientboundSpawnEntityPacket)
            register(0x02, ClientboundEntityAnimationPacket)
            register(0x03, ClientboundAwardStatisticsPacket)
            register(0x04, ClientboundAcknowledgeBlockChangePacket)
            register(0x05, ClientboundBlockDestructionPacket)
            register(0x06, ClientboundBlockEntityDataPacket)
            register(0x07, ClientboundBlockEventPacket)
            register(0x08, ClientboundBlockUpdatePacket)
            register(0x09, ClientboundBossEventPacket)
            register(0x0A, ClientboundChangeDifficultyPacket)
            register(0x0B, ClientboundChunkBatchFinishedPacket)
            register(0x0C, ClientboundChunkBatchStartPacket)
            register(0x0D, ClientboundChunksBiomesPacket)
            register(0x0E, ClientboundClearTitlesPacket)
            register(0x0F, ClientboundCommandSuggestionsPacket)
            register(0x10, ClientboundCommandsPacket)
            register(0x11, ClientboundContainerClosePacket)
//            register(0x12, ClientboundContainerSetContentPacket)
            register(0x13, ClientboundContainerSetDataPacket)
//            register(0x14, ClientboundContainerSetSlotPacket)
            register(0x15, ClientboundCookieRequestPacket)
            register(0x16, ClientboundCooldownPacket)
            register(0x17, ClientboundCustomChatCompletionsPacket)
            register(0x18, ClientboundCustomPayloadPacket)
            register(0x19, ClientboundDamageEventPacket)
//            register(0x1A, ClientboundDebugBlockValuePacket)
//            register(0x1B, ClientboundDebugChunkValuePacket)
//            register(0x1C, ClientboundDebugEntityValuePacket)
//            register(0x1D, ClientboundDebugEventPacket)
//            register(0x1E, ClientboundDebugSamplePacket)
            register(0x1F, ClientboundDeleteChatPacket)
            register(0x20, ClientboundDisconnectPlayPacket)
            register(0x21, ClientboundDisguisedChatMessagePacket)
            register(0x22, ClientboundEntityEventPacket)
            register(0x23, ClientboundTeleportEntityPacket)
//            register(0x24, ClientboundExplodePacket)
            register(0x25, ClientboundUnloadChunkPacket)
            register(0x26, ClientboundGameEventPacket)
            register(0x27, ClientboundGameRuleValuesPacket)
            register(0x28, ClientboundTestHighlightPositionPacket)
            register(0x29, ClientboundOpenHorseScreenPacket)
            register(0x2A, ClientboundHurtAnimationPacket)
            register(0x2B, ClientboundInitializeWorldBorderPacket)
            register(0x2C, ClientboundKeepAlivePlayPacket)
//            register(0x2D, ClientboundLevelChunkUpdateWithLightPacket)
            register(0x2E, ClientboundLevelEventPacket)
            register(0x2F, ClientboundLevelParticlePacket)
//            register(0x30, ClientboundLightUpdatePacket)
            register(0x31, ClientboundLoginPlayPacket)
            register(0x32, ClientboundLowDiskSpaceWarningPacket)
            register(0x33, ClientboundMapItemDataPacket)
//            register(0x34, ClientboundMerchantOffersPacket)
            register(0x35, ClientboundUpdateEntityPositionPacket)
            register(0x36, ClientboundUpdateEntityPositionAndRotationPacket)
            register(0x37, ClientboundMoveMinecartAlongTrackPacket)
            register(0x38, ClientboundUpdateEntityRotationPacket)
            register(0x39, ClientboundMoveVehiclePacket)
            register(0x3A, ClientboundOpenBookPacket)
            register(0x3B, ClientboundOpenScreenPacket)
            register(0x3C, ClientboundOpenSignEditorPacket)
            register(0x3D, ClientboundPingPacket)
            register(0x3E, ClientboundPongResponsePacket)
//            register(0x3F, ClientboundPlaceGhostRecipePacket)
            register(0x40, ClientboundPlayerAbilitiesPacket)
            register(0x41, ClientboundPlayerChatMessagePacket)
            register(0x42, ClientboundPlayerEndCombatPacket)
            register(0x43, ClientboundPlayerEnterCombatPacket)
            register(0x44, ClientboundPlayerCombatDeathPacket)
            register(0x45, ClientboundPlayerInfoRemovePacket)
            register(0x46, ClientboundPlayerInfoUpdatePacket)
            register(0x47, ClientboundPlayerLookAtPacket)
            register(0x48, ClientboundSynchronizePlayerPositionPacket)
            register(0x49, ClientboundPlayerRotationPacket)
//            register(0x4A, ClientboundRecipeBookAddPacket)
            register(0x4B, ClientboundRecipeBookRemovePacket)
            register(0x4C, ClientboundRecipeBookSettingsPacket)
            register(0x4D, ClientboundRemoveEntitiesPacket)
            register(0x4E, ClientboundRemoveEntityEffectPacket)
            register(0x4F, ClientboundResetScorePacket)
            register(0x50, ClientboundRemoveResourcePackPacket)
            register(0x51, ClientboundAddResourcePackPacket)
            register(0x52, ClientboundRespawnPacket)
            register(0x53, ClientboundSetHeadRotationPacket)
            register(0x54, ClientboundUpdateSectionBlockPacket)
            register(0x55, ClientboundSelectAdvancementsTabPacket)
            register(0x56, ClientboundServerDataPacket)
            register(0x57, ClientboundSetActionBarTextPacket)
            register(0x58, ClientboundSetBorderCenterPacket)
            register(0x59, ClientboundSetBorderLeapSizePacket)
            register(0x5A, ClientboundSetBorderSizePacket)
            register(0x5B, ClientboundSetBorderWarningDelayPacket)
            register(0x5C, ClientboundSetBorderWarningDistancePacket)
            register(0x5D, ClientboundSetCameraPacket)
            register(0x5E, ClientboundSetCenterChunkPacket)
            register(0x5F, ClientboundSetRenderDistancePacket)
//            register(0x60, ClientboundSetCursorItemPacket)
            register(0x61, ClientboundSetDefaultSpawnPositionPacket)
            register(0x62, ClientboundSetDisplayObjectivePacket)
//            register(0x63, ClientboundSetEntityMetadataPacket)
            register(0x64, ClientboundLinkEntitiesPacket)
            register(0x65, ClientboundSetEntityVelocityPacket)
//            register(0x66, ClientboundSetEquipmentPacket)
            register(0x67, ClientboundSetExperiencePacket)
            register(0x68, ClientboundSetHealthPacket)
            register(0x69, ClientboundSetCarriedItemPacket)
            register(0x6A, ClientboundUpdateObjectivePacket)
            register(0x6B, ClientboundSetPassengersPacket)
//            register(0x6C, ClientboundSetPlayerInventorySlotPacket)
//            register(0x6D, ClientboundSetPlayerTeamPacket)
            register(0x6E, ClientboundUpdateScorePacket)
            register(0x6F, ClientboundSetSimulationDistancePacket)
            register(0x70, ClientboundSetSubtitleTextPacket)
            register(0x71, ClientboundSetTimePacket)
            register(0x72, ClientboundSetTitleTextPacket)
            register(0x73, ClientboundSetTitleAnimationTimesPacket)
            register(0x74, ClientboundEntitySoundEffectPacket)
            register(0x75, ClientboundSoundEffectPacket)
            register(0x76, ClientboundStartConfigurationPacket)
            register(0x77, ClientboundStopSoundPacket)
            register(0x78, ClientboundStoreCookiePacket)
            register(0x79, ClientboundSystemChatMessagePacket)
            register(0x7A, ClientboundSetTabListHeaderAndFooterPacket)
            register(0x7B, ClientboundTagQueryResponsePacket)
            register(0x7C, ClientboundPickupItemPacket)
            register(0x7D, ClientboundSynchronizeVehiclePositionPacket)
            register(0x7E, ClientboundTestInstanceBlockStatusPacket)
            register(0x7F, ClientboundSetTickingStatePacket)
            register(0x80, ClientboundStepTickPacket)
            register(0x81, ClientboundTransferPacket)
//            register(0x82, ClientboundUpdateAdvancementsPacket)
            register(0x83, ClientboundUpdateAttributesPacket)
            register(0x84, ClientboundEntityEffectPacket)
//            register(0x85, ClientboundUpdateRecipesPacket)
            register(0x86, ClientboundUpdateTagsPacket)
            register(0x87, ClientboundProjectilePowerPacket)
            register(0x88, ClientboundCustomReportDetailsPacket)
            register(0x89, ClientboundServerLinksPacket)
            register(0x8A, ClientboundWaypointPacket)
            register(0x8B, ClientboundClearDialogPacket)
            register(0x8C, ClientboundShowDialogPacket)
        }
    }

    val serverboundGameProtocols = ProtocolStateRegistry().apply {
        register(ProtocolState.HANDSHAKE) {
            register(0x00, ServerboundHandshakePacket)
        }
        register(ProtocolState.STATUS) {
            register(0x00, ServerboundStatusRequestPacket)
            register(0x01, ServerboundPingRequestPacket)
        }
        register(ProtocolState.LOGIN) {
            register(0x00, ServerboundLoginStartPacket)
            register(0x01, ServerboundKeyPacket)
            register(0x02, ServerboundCustomQueryAnswerPacket)
            register(0x03, ServerboundLoginAcknowledgedPacket)
            register(0x04, ServerboundCookieResponsePacket)
        }
        register(ProtocolState.CONFIGURATION) {
            register(0x00, ServerboundCookieResponsePacket)
            register(0x01, ServerboundCookieResponsePacket)
            register(0x02, ServerboundCustomPayloadPacket)
            register(0x03, ServerboundAckFinishConfigurationPacket)
            register(0x04, ServerboundKeepAliveConfigurationPacket)
            register(0x05, ServerboundPongConfigurationPacket)
            register(0x07, ServerboundSelectKnownPacksPacket)
            register(0x08, ServerboundCustomClickActionPacket)
            register(0x09, ServerboundAcceptCodeOfConductPacket)
        }
        register(ProtocolState.PLAY) {
            register(0x00, ServerboundAcceptTeleportationPacket)
            register(0x01, ServerboundAttackActionPacket)
            register(0x02, ServerboundQueryBlockEntityTagPacket)
            register(0x03, ServerboundBundleItemSelectedPacket)
            register(0x04, ServerboundChangeDifficultyPacket)
            register(0x05, ServerboundChangeGameModePacket)
            register(0x06, ServerboundAcknowledgeChatMessagePacket)
            register(0x07, ServerboundChatCommandPacket)
            register(0x08, ServerboundSignedChatCommandPacket)
            register(0x09, ServerboundChatMessagePacket)
            register(0x0A, ServerboundUpdateChatSessionPacket)
            register(0x0B, ServerboundChunkBatchReceivedPacket)
            register(0x0C, ServerboundClientCommandPacket)
            register(0x0D, ServerboundClientTickEndPacket)
            register(0x0E, ServerboundClientInformationPacket)
            register(0x0F, ServerboundCommandSuggestionRequestPacket)
            register(0x10, ServerboundConfigurationAcknowledgedPacket)
            register(0x11, ServerboundContainerClickButtonPacket)
//            register(0x12, ServerboundContainerClickPacket)
            register(0x13, ServerboundContainerClosePacket)
//            register(0x14, ServerboundChangeContainerSlotStatePacket)
            register(0x15, ServerboundCookieResponsePacket)
            register(0x16, ServerboundCustomPayloadPacket)
//            register(0x17, ServerboundDebugSubscriptionRequestPacket)
            register(0x18, ServerboundEditBookPacket)
            register(0x19, ServerboundQueryEntityTagPacket)
            register(0x1A, ServerboundInteractPacket)
            register(0x1B, ServerboundJigsawGeneratePacket)
            register(0x1C, ServerboundKeepAlivePlayPacket)
            register(0x1D, ServerboundLockDifficultyPacket)
            register(0x1E, ServerboundSetPlayerPositionPacket)
            register(0x1F, ServerboundSetPlayerPositionAndRotationPacket)
            register(0x20, ServerboundSetPlayerRotationPacket)
            register(0x21, ServerboundSetPlayerMovementFlagPacket)
            register(0x22, ServerboundMoveVehiclePacket)
            register(0x23, ServerboundPaddleBoatPacket)
            register(0x24, ServerboundPickItemFromBlockPacket)
            register(0x25, ServerboundPickItemFromEntityPacket)
            register(0x26, ServerboundPingRequestPacket)
            register(0x27, ServerboundPlaceRecipePacket)
            register(0x28, ServerboundPlayerAbilitiesPacket)
            register(0x29, ServerboundPlayerActionPacket)
            register(0x2A, ServerboundPlayerCommandPacket)
            register(0x2B, ServerboundPlayerInputPacket)
            register(0x2C, ServerboundPlayerLoadedPacket)
            register(0x2D, ServerboundPongPlayPacket)
            register(0x2E, ServerboundRecipeBookChangeSettingsPacket)
            register(0x2F, ServerboundRecipeBookSeenRecipePacket)
            register(0x30, ServerboundRenameItemPacket)
            register(0x31, ServerboundResourcePackResponsePacket)
            register(0x32, ServerboundSeenAdvancementsPacket)
            register(0x33, ServerboundSelectTradePacket)
            register(0x34, ServerboundSetBeaconPacket)
            register(0x35, ServerboundSetCarriedItemPacket)
            register(0x36, ServerboundSetCommandBlockPacket)
            register(0x37, ServerboundSetCommandMinecartPacket)
//            register(0x38, ServerboundSetCreativeModeSlotPacket)
            register(0x39, ServerboundSetGameRulePacket)
            register(0x3A, ServerboundSetJigsawBlockPacket)
            register(0x3B, ServerboundSetStructureBlockPacket)
            register(0x3C, ServerboundSetTestBlockPacket)
            register(0x3D, ServerboundSignUpdatePacket)
            register(0x3E, ServerboundSpectatorActionPacket)
            register(0x3F, ServerboundSwingPacket)
            register(0x40, ServerboundTeleportToEntityPacket)
            register(0x41, ServerboundTestInstanceBlockActionPacket)
            register(0x42, ServerboundUseItemOnPacket)
            register(0x43, ServerboundUseItemPacket)
            register(0x44, ServerboundCustomClickActionPacket)
        }
    }
}