/*
 * Copyright © 2026 RTAkland
 * Author: RTAkland
 * Date: 2026/9/5
 */

package cn.rtast.libmc.protocol.protocol

import cn.rtast.libmc.protocol.packet.configuration.clientbound.*
import cn.rtast.libmc.protocol.packet.configuration.serverbound.*
import cn.rtast.libmc.protocol.packet.handshake.ServerboundHandshakePacket
import cn.rtast.libmc.protocol.packet.login.clientbound.*
import cn.rtast.libmc.protocol.packet.login.serverbound.ServerboundCustomQueryAnswerPacket
import cn.rtast.libmc.protocol.packet.login.serverbound.ServerboundKeyPacket
import cn.rtast.libmc.protocol.packet.login.serverbound.ServerboundLoginAcknowledgedPacket
import cn.rtast.libmc.protocol.packet.login.serverbound.ServerboundLoginStartPacket
import cn.rtast.libmc.protocol.packet.play.clientbound.*
import cn.rtast.libmc.protocol.packet.play.serverbound.*
import cn.rtast.libmc.protocol.packet.status.clientbound.ClientboundPongResponsePacket
import cn.rtast.libmc.protocol.packet.status.clientbound.ClientboundStatusResponsePacket
import cn.rtast.libmc.protocol.packet.status.serverbound.ServerboundPingRequestPacket
import cn.rtast.libmc.protocol.packet.status.serverbound.ServerboundStatusRequestPacket
import cn.rtast.libmc.protocol.protocol.state.ProtocolState
import cn.rtast.libmc.protocol.protocol.state.ProtocolStateRegistry

internal object GamePacketsProtocolCodec {
    val clientboundGameProtocols = ProtocolStateRegistry().apply {
        register(ProtocolState.STATUS) {
            register(0x00, ClientboundStatusResponsePacket)
            register(0x01, ClientboundPongResponsePacket)
        }
        register(ProtocolState.LOGIN) {
            register(0x00, ClientboundDisconnectLoginPacket)
            register(0x01, ClientboundHelloPacket)
            register(0x02, ClientboundLoginSuccessPacket)
            register(0x03, ClientboundSetCompressionPacket)
            register(0x04, ClientboundCustomQueryPacket)
            register(0x05, ClientboundCookieRequestPacket)
        }
        register(ProtocolState.CONFIGURATION) {
            register(0x00, ClientboundCookieRequestPacket)
            register(0x01, ClientboundCustomPayloadPacket)
            register(0x02, ClientboundDisconnectConfigurationPacket)
            register(0x03, ClientboundFinishConfigurationPacket)
            register(0x04, ClientboundKeepAliveConfigurationPacket)
            register(0x05, ClientboundPingConfigurationPacket)
            register(0x06, ClientboundResetChatPacket)
            register(0x07, ClientboundRegistryDataPacket)
            register(0x08, ClientboundRemoveResourcePackPacket)
            register(0x09, ClientboundAddResourcePackPacket)
            register(0x0a, ClientboundStoreCookiePacket)
            register(0x0b, ClientboundTransferPacket)
            register(0x0c, ClientboundUpdateEnabledFeaturesPacket)
            register(0x0d, ClientboundUpdateTagsPacket)
            register(0x0e, ClientboundSelectKnownPacksPacket)
            register(0x0f, ClientboundCustomReportDetailsPacket)
            register(0x10, ClientboundServerLinksPacket)
            register(0x11, ClientboundClearDialogPacket)
            register(0x12, ClientboundConfigurationShowDialogPacket)
            register(0x13, ClientboundCodeOfConductPacket)
        }
        register(ProtocolState.PLAY) {
            register(0x00, ClientboundDelimiterPacket)
            register(0x01, ClientboundSpawnEntityPacket)
            register(0x02, ClientboundEntityAnimationPacket)
            register(0x03, ClientboundAwardStatisticsPacket)
            register(0x04, ClientboundAcknowledgeBlockChangePacket)
            register(0x05, ClientboundBlockDestructionPacket)
            register(0x06, ClientboundBlockEntityDataPacket)
            register(0x07, ClientboundBlockEventPacket)
            register(0x08, ClientboundBlockUpdatePacket)
            register(0x09, ClientboundBossEventPacket)
            register(0x0a, ClientboundChangeDifficultyPacket)
            register(0x0b, ClientboundChunkBatchFinishedPacket)
            register(0x0c, ClientboundChunkBatchStartPacket)
            register(0x0d, ClientboundChunksBiomesPacket)
            register(0x0e, ClientboundClearTitlesPacket)
            register(0x0f, ClientboundCommandSuggestionsPacket)
            register(0x10, ClientboundCommandsPacket)
            register(0x11, ClientboundContainerClosePacket)
//            register(0x12, ClientboundContainerSetContentPacket)
            register(0x13, ClientboundContainerSetDataPacket)
//            register(0x14, ClientboundContainerSetSlotPacket)
            register(0x15, ClientboundCookieRequestPacket)
            register(0x16, ClientboundCooldownPacket)
            register(0x17, ClientboundCustomChatCompletionsPacket)
            register(0x18, ClientboundCustomPayloadPacket)
            register(0x19, ClientboundDamageEventPacket)
//            register(0x1a, ClientboundDebugBlockValuePacket)
//            register(0x1b, ClientboundDebugChunkValuePacket)
//            register(0x1c, ClientboundDebugEntityValuePacket)
//            register(0x1d, ClientboundDebugEventPacket)
//            register(0x1e, ClientboundDebugSamplePacket)
            register(0x1f, ClientboundDeleteChatPacket)
            register(0x20, ClientboundDisconnectPlayPacket)
            register(0x21, ClientboundDisguisedChatMessagePacket)
            register(0x22, ClientboundEntityEventPacket)
            register(0x23, ClientboundTeleportEntityPacket)
//            register(0x24, ClientboundExplodePacket)
            register(0x25, ClientboundUnloadChunkPacket)
            register(0x26, ClientboundGameEventPacket)
            register(0x27, ClientboundGameRuleValuesPacket)
            register(0x28, ClientboundTestHighlightPositionPacket)
            register(0x29, ClientboundOpenHorseScreenPacket)
            register(0x2a, ClientboundHurtAnimationPacket)
            register(0x2b, ClientboundInitializeWorldBorderPacket)
            register(0x2c, ClientboundKeepAlivePlayPacket)
//            register(0x2d, ClientboundLevelChunkUpdateWithLightPacket)
            register(0x2e, ClientboundLevelEventPacket)
//            register(0x2f, ClientboundParticlePacket)
//            register(0x30, ClientboundLightUpdatePacket)
            register(0x31, ClientboundLoginPlayPacket)
            register(0x32, ClientboundLowDiskSpaceWarningPacket)
            register(0x33, ClientboundMapItemDataPacket)
//            register(0x34, ClientboundMerchantOffersPacket)
            register(0x35, ClientboundUpdateEntityPositionPacket)
            register(0x36, ClientboundUpdateEntityPositionAndRotationPacket)
            register(0x37, ClientboundMoveMinecartAlongTrackPacket)
            register(0x38, ClientboundUpdateEntityRotationPacket)
            register(0x39, ClientboundMoveVehiclePacket)
            register(0x3a, ClientboundOpenBookPacket)
            register(0x3b, ClientboundOpenScreenPacket)
            register(0x3c, ClientboundOpenSignEditorPacket)
            register(0x3d, ClientboundPingPacket)
            register(0x3e, ClientboundPongResponsePacket)
//            register(0x3f, ClientboundPlaceGhostRecipePacket)
            register(0x40, ClientboundPlayerAbilitiesPacket)
            register(0x41, ClientboundPlayerChatMessagePacket)
            register(0x42, ClientboundPlayerEndCombatPacket)
            register(0x43, ClientboundPlayerEnterCombatPacket)
            register(0x44, ClientboundPlayerCombatDeathPacket)
            register(0x45, ClientboundPlayerInfoRemovePacket)
//            register(0x46, ClientboundPlayerInfoUpdatePacket)
            register(0x47, ClientboundPlayerLookAtPacket)
            register(0x48, ClientboundSynchronizePlayerPositionPacket)
            register(0x49, ClientboundPlayerRotationPacket)
//            register(0x4a, ClientboundRecipeBookAddPacket)
//            register(0x4b, ClientboundRecipeBookRemovePacket)
//            register(0x4c, ClientboundRecipeBookSettingsPacket)
            register(0x4d, ClientboundRemoveEntitiesPacket)
            register(0x4e, ClientboundRemoveEntityEffectPacket)
            register(0x4f, ClientboundResetScorePacket)
            register(0x50, ClientboundRemoveResourcePackPacket)
            register(0x51, ClientboundAddResourcePackPacket)
            register(0x52, ClientboundRespawnPacket)
            register(0x53, ClientboundSetHeadRotationPacket)
            register(0x54, ClientboundUpdateSectionBlockPacket)
            register(0x55, ClientboundSelectAdvancementsTabPacket)
            register(0x56, ClientboundServerDataPacket)
            register(0x57, ClientboundSetActionBarTextPacket)
            register(0x58, ClientboundSetBorderCenterPacket)
            register(0x59, ClientboundSetBorderLeapSizePacket)
            register(0x5a, ClientboundSetBorderSizePacket)
            register(0x5b, ClientboundSetBorderWarningDelayPacket)
            register(0x5c, ClientboundSetBorderWarningDistancePacket)
            register(0x5d, ClientboundSetCameraPacket)
            register(0x5e, ClientboundSetCenterChunkPacket)
            register(0x5f, ClientboundSetRenderDistancePacket)
//            register(0x60, ClientboundSetCursorItemPacket)
            register(0x61, ClientboundSetDefaultSpawnPositionPacket)
            register(0x62, ClientboundSetDisplayObjectivePacket)
//            register(0x63, ClientboundSetEntityMetadataPacket)
            register(0x64, ClientboundLinkEntitiesPacket)
            register(0x65, ClientboundSetEntityVelocityPacket)
//            register(0x66, ClientboundSetEquipmentPacket)
            register(0x67, ClientboundSetExperiencePacket)
            register(0x68, ClientboundSetHealthPacket)
            register(0x69, ClientboundSetCarriedItemPacket)
            register(0x6a, ClientboundUpdateObjectivePacket)
            register(0x6b, ClientboundSetPassengersPacket)
//            register(0x6c, ClientboundSetPlayerInventorySlotPacket)
//            register(0x6d, ClientboundSetPlayerTeamPacket)
            register(0x6e, ClientboundUpdateScorePacket)
            register(0x6f, ClientboundSetSimulationDistancePacket)
            register(0x70, ClientboundSetSubtitleTextPacket)
            register(0x71, ClientboundSetTimePacket)
            register(0x72, ClientboundSetTitleTextPacket)
            register(0x73, ClientboundSetTitleAnimationTimesPacket)
            register(0x74, ClientboundEntitySoundEffectPacket)
            register(0x75, ClientboundSoundEffectPacket)
            register(0x76, ClientboundStartConfigurationPacket)
            register(0x77, ClientboundStopSoundPacket)
            register(0x78, ClientboundStoreCookiePacket)
            register(0x79, ClientboundSystemChatMessagePacket)
            register(0x7a, ClientboundSetTabListHeaderAndFooterPacket)
            register(0x7b, ClientboundTagQueryResponsePacket)
            register(0x7c, ClientboundPickupItemPacket)
            register(0x7d, ClientboundSynchronizeVehiclePositionPacket)
            register(0x7e, ClientboundTestInstanceBlockStatusPacket)
            register(0x7f, ClientboundSetTickingStatePacket)
            register(0x80, ClientboundStepTickPacket)
            register(0x81, ClientboundTransferPacket)
//            register(0x82, ClientboundUpdateAdvancementsPacket)
            register(0x83, ClientboundUpdateAttributesPacket)
            register(0x84, ClientboundEntityEffectPacket)
//            register(0x85, ClientboundUpdateRecipesPacket)
            register(0x86, ClientboundUpdateTagsPacket)
            register(0x87, ClientboundProjectilePowerPacket)
            register(0x88, ClientboundCustomReportDetailsPacket)
            register(0x89, ClientboundServerLinksPacket)
            register(0x8a, ClientboundWaypointPacket)
            register(0x8b, ClientboundClearDialogPacket)
            register(0x8c, ClientboundShowDialogPacket)
        }
    }

    val serverboundGameProtocols = ProtocolStateRegistry().apply {
        register(ProtocolState.HANDSHAKE) {
            register(0x00, ServerboundHandshakePacket)
        }
        register(ProtocolState.STATUS) {
            register(0x00, ServerboundStatusRequestPacket)
            register(0x01, ServerboundPingRequestPacket)
        }
        register(ProtocolState.LOGIN) {
            register(0x00, ServerboundLoginStartPacket)
            register(0x01, ServerboundKeyPacket)
            register(0x02, ServerboundCustomQueryAnswerPacket)
            register(0x03, ServerboundLoginAcknowledgedPacket)
            register(0x04, ServerboundCookieResponsePacket)
        }
        register(ProtocolState.CONFIGURATION) {
            register(0x00, ServerboundCookieResponsePacket)
            register(0x01, ServerboundCookieResponsePacket)
            register(0x02, ServerboundCustomPayloadPacket)
            register(0x03, ServerboundAckFinishConfigurationPacket)
            register(0x04, ServerboundKeepAliveConfigurationPacket)
            register(0x05, ServerboundPongConfigurationPacket)
            register(0x07, ServerboundSelectKnownPacksPacket)
            register(0x08, ServerboundCustomClickActionPacket)
            register(0x09, ServerboundAcceptCodeOfConductPacket)
        }
        register(ProtocolState.PLAY) {
            register(0x00, ServerboundAcceptTeleportationPacket)
            register(0x01, ServerboundAttackActionPacket)
            register(0x02, ServerboundQueryBlockEntityTagPacket)
            register(0x03, ServerboundBundleItemSelectedPacket)
            register(0x04, ServerboundChangeDifficultyPacket)
            register(0x05, ServerboundChangeGameModePacket)
            register(0x06, ServerboundAcknowledgeChatMessagePacket)
            register(0x07, ServerboundChatCommandPacket)
            register(0x08, ServerboundSignedChatCommandPacket)
            register(0x09, ServerboundChatMessagePacket)
            register(0x0a, ServerboundUpdateChatSessionPacket)
            register(0x0b, ServerboundChunkBatchReceivedPacket)
            register(0x0c, ServerboundClientCommandPacket)
            register(0x0d, ServerboundClientTickEndPacket)
            register(0x0e, ServerboundClientInformationPacket)
            register(0x0f, ServerboundCommandSuggestionRequestPacket)
            register(0x10, ServerboundConfigurationAcknowledgedPacket)
            register(0x11, ServerboundContainerClickButtonPacket)
//            register(0x12, ServerboundContainerClickPacket)
            register(0x13, ServerboundContainerClosePacket)
//            register(0x14, ServerboundChangeContainerSlotStatePacket)
            register(0x15, ServerboundCookieResponsePacket)
            register(0x16, ServerboundCustomPayloadPacket)
//            register(0x17, ServerboundDebugSubscriptionRequestPacket)
            register(0x18, ServerboundEditBookPacket)
            register(0x19, ServerboundQueryEntityTagPacket)
            register(0x1a, ServerboundInteractPacket)
            register(0x1b, ServerboundJigsawGeneratePacket)
            register(0x1c, ServerboundKeepAlivePlayPacket)
            register(0x1d, ServerboundLockDifficultyPacket)
            register(0x1e, ServerboundSetPlayerPositionPacket)
            register(0x1f, ServerboundSetPlayerPositionAndRotationPacket)
            register(0x20, ServerboundSetPlayerRotationPacket)
            register(0x21, ServerboundSetPlayerMovementFlagPacket)
            register(0x22, ServerboundMoveVehiclePacket)
            register(0x23, ServerboundPaddleBoatPacket)
            register(0x24, ServerboundPickItemFromBlockPacket)
            register(0x25, ServerboundPickItemFromEntityPacket)
            register(0x26, ServerboundPingRequestPacket)
            register(0x27, ServerboundPlaceRecipePacket)
            register(0x28, ServerboundPlayerAbilitiesPacket)
            register(0x29, ServerboundPlayerActionPacket)
            register(0x2a, ServerboundPlayerCommandPacket)
            register(0x2b, ServerboundPlayerInputPacket)
            register(0x2c, ServerboundPlayerLoadedPacket)
            register(0x2d, ServerboundPongPlayPacket)
            register(0x2e, ServerboundRecipeBookChangeSettingsPacket)
            register(0x2f, ServerboundRecipeBookSeenRecipePacket)
            register(0x30, ServerboundRenameItemPacket)
            register(0x31, ServerboundResourcePackResponsePacket)
            register(0x32, ServerboundSeenAdvancementsPacket)
            register(0x33, ServerboundSelectTradePacket)
            register(0x34, ServerboundSetBeaconPacket)
            register(0x35, ServerboundSetCarriedItemPacket)
            register(0x36, ServerboundSetCommandBlockPacket)
            register(0x37, ServerboundSetCommandMinecartPacket)
//            register(0x38, ServerboundSetCreativeModeSlotPacket)
            register(0x39, ServerboundSetGameRulePacket)
            register(0x3a, ServerboundSetJigsawBlockPacket)
            register(0x3b, ServerboundSetStructureBlockPacket)
            register(0x3c, ServerboundSetTestBlockPacket)
            register(0x3d, ServerboundSignUpdatePacket)
            register(0x3e, ServerboundSpectatorActionPacket)
            register(0x3f, ServerboundSwingPacket)
            register(0x40, ServerboundTeleportToEntityPacket)
            register(0x41, ServerboundTestInstanceBlockActionPacket)
            register(0x42, ServerboundUseItemOnPacket)
            register(0x43, ServerboundUseItemPacket)
            register(0x44, ServerboundCustomClickActionPacket)
        }
    }
}